### ISSUE TITLE
什么时候会出EasyMVVM？

### ISSUE THREAD

**Issue by near2sea** [Meituan-Dianping/EasyReact#67]
期待

**Comment by ValiantCat** [comment]
+1

**Comment by WilliamZang** [comment]
会先出 EasyReactSwift，目前已经立项了 https://github.com/meituan/EasyReactSwift

**Comment by ZhiyuWong** [comment]
+1

**Comment by YanweiLi** [comment]
期待！！！

**Comment by PrismXX** [comment]
- - 要做新项目了，只能先EasyReact起来了，期待EasyMVVM

**Comment by huangjianke** [comment]
同期待+1


**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by WilliamZang** [comment]
https://github.com/Meituan-Dianping/EasyMVVM
