### ISSUE TITLE
如何在复用的组件中正确使用EZR

### ISSUE THREAD

**Issue by HarrisonXi** [Meituan-Dianping/EasyReact#75]
**Is your feature request related to a problem? Please describe.**
目前来看，大部分EZR的自动销毁放在对应object的dealloc时进行，在UITableViewCell这种需要复用的情况下，没有找到合适方便的方法进行处理

**Describe the solution you'd like**
可以在底层自动处理对应的复用场景，或者提供便利的方法供手动销毁原来的binding

**Additional context**
例如期望在cellForIndexPath里只需要写一句，就可以反复自动绑定
`EZR_PATH(cell.textLabel, text) = EZR_PATH(cellModel, text);`
目前来说这么写一会儿就卡死了

**Comment by WilliamZang** [comment]
在EasyMVVM的设计中，有一个叫做binder的概念，然后UITableViewCell在reuse的时候会调用binder的clean功能解除绑定，可惜EasyMVVM还没有发布出来。单纯的EasyReact还只是一个功能库，需要上层的应用层来丰富。不过你可以尝试做一个专门用来解除绑定的binder封装

**Comment by HarrisonXi** [comment]
感谢，了解大意了

**Comment by WilliamZang** [comment]
https://github.com/Meituan-Dianping/EasyMVVM
