### ISSUE TITLE
MemoryManagement.md 文档的最后一段示例代码是不是写错了？

### ISSUE THREAD

**Issue by DaoPinWong** [Meituan-Dianping/EasyReact#81]
NSObject *obj = [NSObject new];
[[obj listen:nodeA] withBlock:^(id  _Nullable next) {
    NSLog(@"nodeA value = %@", next);
}];
[[obj listen:nodeB] withBlock:^(id  _Nullable next) {
    NSLog(@"nodeB value = %@", next);
}];

**Comment by indulgeIn** [comment]
没有写错呀

**Comment by DaoPinWong** [comment]
不好意思，没怎么看源码就来提问了，看了一遍源码是我理解错了

**Comment by DaoPinWong** [comment]
> 没有写错呀

不好意思，没怎么看源码就来提问了，看了一遍源码是我理解错了
